controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    right_crane_plus_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    right_crane_plus_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    left_crane_plus_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    left_crane_plus_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    joint_state_controller:
      type: joint_state_controller/JointStateController

right_crane_plus_arm_controller:
  ros__parameters:
    joints:
      - right_crane_plus_joint1
      - right_crane_plus_joint2
      - right_crane_plus_joint3
      - right_crane_plus_joint4

right_crane_plus_gripper_controller:
  ros__parameters:
    joints:
      - right_crane_plus_joint_hand

left_crane_plus_arm_controller:
  ros__parameters:
    joints:
      - left_crane_plus_joint1
      - left_crane_plus_joint2
      - left_crane_plus_joint3
      - left_crane_plus_joint4

left_crane_plus_gripper_controller:
  ros__parameters:
    joints:
      - left_crane_plus_joint_hand