controller_names:
  - right_crane_plus_arm_controller
  - right_crane_plus_gripper_controller
  - left_crane_plus_arm_controller
  - left_crane_plus_gripper_controller

right_crane_plus_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - right_crane_plus_joint1
    - right_crane_plus_joint2
    - right_crane_plus_joint3
    - right_crane_plus_joint4

right_crane_plus_gripper_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - right_crane_plus_joint_hand

left_crane_plus_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - left_crane_plus_joint1
    - left_crane_plus_joint2
    - left_crane_plus_joint3
    - left_crane_plus_joint4

left_crane_plus_gripper_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - left_crane_plus_joint_hand
